# Base image
FROM nginx:latest

# Remove default NGINX configurations
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom NGINX configuration
COPY nginx/default.conf /etc/nginx/conf.d/

# Expose port 80 for NGINX
EXPOSE 80